[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/fr_feed.xml"
  to = "/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/fr/products"
  to = "/fr/compatibilities/"
  status = 301
  force = true

[[redirects]]
  from = "/gladys-community-package"
  to = "/fr/gladys-community-package"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/gladys-community-package"
  to = "/en/gladys-community-package"
  status = 302
  force = true

[[redirects]]
  from = "/gateway"
  to = "/fr/gladys-community-package"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/gateway"
  to = "/en/gladys-community-package"
  status = 302
  force = true

[[redirects]]
  from = "http://xenodochial-bardeen-b5e86a.netlify.com/*"
  to = "http://gladysassistant.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://xenodochial-bardeen-b5e86a.netlify.com/*"
  to = "https://gladysassistant.com/:splat"
  status = 301
  force = true
